name: myfirstoauth2
description: "A flutter package for beginners to easly authenticate via OAuth2 using OAuth2 packages."
version: 1.0.3
repository: https://github.com/albertoboccolini/myfirstoauth2

environment:
  sdk: 3.2.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  github: ^9.19.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1