name: myfirstoauth2
description: "A flutter package for beginners to easly authenticate via OAuth2 using OAuth2 packages."
version: 1.0.0
repository: https://github.com/albertoboccolini/myfirstoauth2

environment:
  sdk: 3.1.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0